---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-59c116e99d544b7f8faa28cef5e98401
  name: wave-gitops-config
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/anasinnyk/wave-gitops-config.git
  deployment_type: kustomize
  path: ./flux/resources/prometheus/vm-stack
  source_type: git
  url: ssh://git@github.com/anasinnyk/wave-gitops-config.git
